triptales/urls.py
"""Urls for triptales app"""

from django.conf.urls import include
from django.urls import path
from triptales import views

app_name = 'triptales'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('quiz/', views.quiz, name='quiz'),
    path('FAQ/', views.FAQ, name='FAQ'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('quiz', views.quiz, name='quiz'),
    path('basetest', views.basetest, name='basetest'),
    path('basetest/<str:continent>', views.basetest, name='basetest'),
    path('posts/<str:continent_name>/', views.posts_by_continent, name='posts_by_continent'),
    path('posts/detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create_post/', views.create_post, name='create_post'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('add_country/', views.add_country, name='add_country'),
    path('add_location/', views.add_location, name='add_location'),
    path('like_post/', views.LikePostView.as_view(), name='like_post'),
    path('save_post/', views.SavePostView.as_view(), name='save_post'),
]

triptales_project/urls.py
from django.contrib import admin, messages
from django.urls import path, reverse
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from triptales import views

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('triptales:register_profile')

    def form_invalid(self, form):
        response = super().form_invalid(form)
        print(form.errors)
        messages.error(self.request, form.errors)
        return response
    

    
urlpatterns = [
    path('get_all_posts/<str:type>/', views.get_all_posts, name='get_all_posts'),
    path('filter_sort_by/<str:sort_type>/<str:filter_type>/<str:continent>/', views.filter_sort_by, name='filter_sort_by'),
    path('', views.index, name='index'),
    path('triptales/', include('triptales.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

triptales/forms.py
"""Forms for the triptales app."""
from django import forms
from triptales.models import Country, Location, VacationPost, UserProfile, Comment
from django.contrib.auth.models import User


class CountryForm(forms.ModelForm):
    name = forms.CharField(help_text="Please enter the name of the country.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Country
        fields = ('name', 'continent')
        help_texts = {
            'continent': 'Please select the continent of the country.'}



class LocationForm(forms.ModelForm):
    name = forms.CharField(help_text="Please enter the name of the location.")
    country = forms.ModelChoiceField(queryset=Country.objects.all().order_by('name'),
                                     help_text="Please choose the country where this location is.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    vibe = forms.RadioSelect()
    setting = forms.RadioSelect()
    travelPartners = forms.RadioSelect()
    climate = forms.RadioSelect()

    class Meta:
        model = Location
        exclude = ('views', 'posts')
        help_texts = {'vibe': 'What kind of vibe does this place give off?',
                      'setting': 'What type of setting is it?',
                      'travelPartners': 'What kind of partner is most suitable?',
                      'climate': 'What is the weather like here?', }


class CommentForm(forms.ModelForm):
    text = forms.CharField(help_text="")

    class Meta:
        model = Comment
        fields = ('text',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture', 'bio')


class VacationPostForm(forms.ModelForm):
    location = forms.ModelChoiceField(queryset=Location.objects.all().order_by('name'), empty_label="Select Location", required=False)
    title = forms.CharField(help_text="Title")
    text = forms.CharField(help_text="Caption Here.")
    image = forms.ImageField(help_text="Please upload the image you wish to share")

    def __init__(self, *args, **kwargs):
        super(VacationPostForm, self).__init__(*args, **kwargs)
        self.fields['location'].queryset = Location.objects.all().order_by(
            'name')  # Set the queryset for the location field

    def clean_location(self):
        location = self.cleaned_data['location']
        if location and location in self.fields['location'].queryset:
            return location
        raise forms.ValidationError("Invalid location selection.")

    class Meta:
        model = VacationPost
        fields = ['title', 'text', 'image', 'location']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }

triptales/views.py
"""Views for the triptales app."""

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from datetime import datetime
from triptales.forms import *
from triptales.models import *
from django.views import View
from django.utils.decorators import method_decorator
from django.http import JsonResponse


# Create your views here.
def index(request):
    context_dict = {}

    # visitor_cookie_handler(request)

    response = render(request, 'triptales/index.html', context=context_dict)
    return response


def posts_by_continent(request, continent_name):
    continent_name = continent_name.replace('-', '').replace('.png', '').replace('_', ' ')

    countries = Country.objects.filter(continent__iexact=continent_name)

    posts = VacationPost.objects.filter(country__in=countries).distinct()
    posts_dic = {}
    for p in posts:
        if request.user.is_authenticated:
            current_userprofile = UserProfile.objects.get_or_create(user=request.user)[0]
            is_liked = True if p in current_userprofile.liked_posts.all() else False
            is_saved = True if p in current_userprofile.saved_posts.all() else False
        else:
            is_liked = False
            is_saved = False

        posts_dic[p] = {'is_liked': is_liked, 'is_saved': is_saved}

    context_dict = {
        'continent_name': continent_name,
        'posts': posts,
        'posts_dic': posts_dic,
        'countries': countries,
    }

    return render(request, 'triptales/posts_by_continent.html', context=context_dict)


def post_detail(request, post_id):
    post = get_object_or_404(VacationPost, pk=post_id)

    if request.user.is_authenticated:
        current_userprofile = UserProfile.objects.get_or_create(user=request.user)[0]
        is_liked = True if post in current_userprofile.liked_posts.all() else False
        is_saved = True if post in current_userprofile.saved_posts.all() else False
    else:
        is_liked = False
        is_saved = False

    context = {'post': post, 'is_liked': is_liked, 'is_saved': is_saved}
    return render(request, 'triptales/post_detail.html', context)


@login_required
def create_post(request):
    locations = Location.objects.all()
    form = VacationPostForm()

    if request.method == 'POST':
        form = VacationPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.likes = 0
            currentLocation = Location.objects.get(id=post.location.id)
            post.country = currentLocation.country
            post.title
            post.save()
            form.save_m2m()
            return redirect(reverse('triptales:index'))  # Redirect to the desired page after successful form submission
        else:
            print(form.errors)


    return render(request, 'triptales/create_post.html', {'form': form, 'locations': locations})

@login_required
def add_country(request):

    form = CountryForm()

    if request.method == 'POST':
        form = CountryForm(request.POST)
        if form.is_valid():
            country = form.save(commit=True)
            country.posts = 0
            country.views = 0
            country.save()
            return redirect(reverse('triptales:index'))
        else:
            print(form.errors)

    return render(request, 'triptales/add_country.html', {'form': form })

@login_required
def add_location(request):
    form = LocationForm()

    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            location = form.save(commit=False)
            location.posts = 0
            location.views = 0
            location.save()
            return redirect(reverse('triptales:index'))
        else:
            print(form.errors)

    return render(request, 'triptales/add_location.html', {'form':form})

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def about(request):
    visitor_cookie_handler(request)
    return render(request, 'triptales/about.html')

def quiz(request):
    visitor_cookie_handler(request)
    return render(request, 'triptales/quiz.html')


def FAQ(request):
    visitor_cookie_handler(request)
    return render(request, 'triptales/FAQ.html')


def contact_us(request):
    visitor_cookie_handler(request)
    return render(request, 'triptales/contact_us.html')

def basetest(request, continent):
    context_dict = {'continent': continent}
    return render(request, 'triptales/basetest.html', context=context_dict)


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('triptales:index'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'triptales/profile_registration.html', context_dict)


@login_required
def edit_profile(request):
    user_profile = UserProfile.objects.get_or_create(user=request.user)[0]
    form = UserProfileForm({'bio': user_profile.bio,
                            'picture': user_profile.picture})

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('triptales:profile', request.user.username)
        else:
            print(form.errors)

    context_dict = {'user_profile': user_profile, 'form': form}
    return render(request, 'triptales/userprofile_form_base.html', context_dict)


class ProfileView(View):
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            user = User.objects.get(username=username)
            user_profile = UserProfile.objects.get_or_create(user=user)[0]
        except User.DoesNotExist:
            return None
        except TypeError:
            return redirect(reverse('triptales:index'))

        liked_posts = user_profile.liked_posts.all()
        saved_posts = user_profile.saved_posts.all()
        user_posts = user_profile.posts_made.all()

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'liked_posts': liked_posts,
                        'saved_posts': saved_posts,
                        'user_posts': user_posts}
        
        return render(request, 'triptales/profile.html', context_dict)

def get_all_posts(request, type):
    if type == "likes":
        posts = VacationPost.objects.order_by('-likes')[:6] #number of posts displayed on page can be altered 
    if type == "recent":
        posts = VacationPost.objects.order_by('-created_at')[:6]
    posts_data = [{'id': post.id, 'title': post.title, 'likes': post.likes, 'text': post.text, 'author': post.author.username, 'country_name': post.country.name, 'location_name': post.location.name, 'created_at': post.created_at,  'img_url': post.image.url if post.image else None} for post in posts]
    response_data = {'posts': posts_data}
    return JsonResponse(response_data, safe=False)


def filter_sort_by(request, sort_type, filter_type, continent):
    countries = Country.objects.filter(continent__iexact=continent)
    if filter_type != "none":
        countries = countries.filter(id=filter_type)
    posts = VacationPost.objects.filter(country__in=countries).distinct()
    if sort_type == "sort-liked":
        posts = posts.order_by('-likes')
    elif sort_type == "sort-oldest":
        posts = posts.order_by('created_at')
    elif sort_type == "sort-recent":
        posts = posts.order_by('-created_at')
    elif sort_type == "least-liked":
        posts = posts.order_by('likes')
    posts_data = [{'id': post.id, 'title': post.title, 'likes': post.likes, 'text': post.text, 'author': post.author.username, 'country_name': post.country.name, 'location_name': post.location.name, 'created_at': post.created_at, 'img_url': post.image.url if post.image else None} for post in posts]
    return JsonResponse(posts_data, safe=False)

class LikePostView(View):
    @method_decorator(login_required)
    def get(self, request):
        post_id = request.GET['post_id']
        try:
            post = VacationPost.objects.get(id=int(post_id))
        except VacationPost.DoesNotExist or ValueError:
            return HttpResponse(-1)

        user_profile = UserProfile.objects.get_or_create(user=request.user)[0]

        if post in user_profile.liked_posts.all():
            user_profile.liked_posts.remove(post)
            post.likes -= 1
        else:
            user_profile.liked_posts.add(post)
            post.likes += 1
        
        # print(f"Post likes: {post.likes}")
        # print(f"User liked posts: {user_profile.liked_posts.all()}")
        post.save()
        return HttpResponse(post.likes)

templates/triptales/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <link rel="icon" href="{% static 'images/favicon.ico' %}">
        <title>
            {% block title_block %}Find Your Holiday With TripTales{% endblock %}
        </title>

        <!-- Bootstrap 5 .css file (needed for templates to work) -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
        <!--Custom styles for this template -->
        <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
        
        <!-- Base Stylesheet -->
        <link rel="stylesheet" href="{% static 'css/triptales/triptalesstyle.css' %}">

        {% comment %} Stylesheets for extensions htmls {% endcomment %}
        {% block extra_css %}{% endblock %}
    </head>
    
    <body>
        <!-- Bootstrap 5 .js file (needed for templates to work) -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        
        <!-- Load corresponding css depending if user is logged in -->
        {% if user.is_authenticated %}
            <link rel="stylesheet" href="{% static 'css/triptales/navbar_signed_in.css' %}">
        {% else %}
            <link rel="stylesheet" href="{% static 'css/triptales/navbar_guest.css' %}">
        {% endif %}
            
        <!-- Whole screen overlay -->
        <div id="maincontent">
            <div id="overlay"></div>

            <!-- NavBar stuff -->
            <div class="left_nav">
                <div class="child2">
                    <a href="{% url 'triptales:index' %}"><button class="button-nav" role="button">Home</button></a>
                </div>
            </div>

            <div class="left_nav">
                <div class="child2">
                    <a href="{% url 'triptales:about' %}"><button class="button-nav" role="button">About</button></a>
                </div>
            </div>

            {% if user.is_authenticated %}
            <div class="right_nav">
                <div class="child2">
                    <a href="{% url 'auth_logout' %}?next=/triptales/"><button class="button-nav" role="button">Logout</button></a>
                </div>
            </div>

            <div class="right_nav">
                <div class="child2">
                    <a href="{% url 'triptales:profile' user.username %}"><button class="button-nav" role="button">Profile</button></a>
                </div>
            </div>

            <div class="right_nav">
                <div class="child2">
                    <a><button class="button-nav" id="button" role="button" onclick="addPopup();">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
                            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" stroke="white" stroke-width="0.8"/>
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" stroke="white" stroke-width="0.8"/>
                        </svg>
                    </button></a>
                </div>
            </div>

                {% else %}
                <div class="right_nav">
                    <div class="child2">
                        <a href="{% url 'registration_register' %}"><button class="button-nav" role="button">Sign Up</button></a>
                    </div>
                </div>
                <div class="right_nav">
                    <div class="child2">
                        <a href="{% url 'auth_login' %}"><button class="button-nav" role="button">Log In</button></a>
                    </div>
                </div>
                {% endif %}

                <div class="nava">
                    <div class="title-nav">
                        <a href="{% url 'triptales:index' %}"><h6 style="margin-bottom: 0px;">TripTales</h6></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- NavBar end -->

        <!-- Popup code -->
        <div id="popup" class="">
            <div class="popupcontrols">
                <span id="popupclose" onclick="">X</span>
            </div>
            <div class="popupcontent">
                <p class="popup_heading">Add Content</p>
                <div class="option_container">
                    <p class="popup_text">Looking to share your holiday with others? Create a post and tell the tale of your trip!</p>
                    <div class="center_but">
                        <a href="{% url 'triptales:create_post' %}"><button class="button-popup" role="button">Create Post</button></a>
                    </div>
                    <p class="popup_text">Missing a country? Add it here!</p>
                    <div class="center_but">
                        <a href="{% url 'triptales:add_country' %}"><button class="button-popup" role="button">Add Country</button></a>
                    </div>
                    <p class="popup_text">Been to a location no one else has been to? Add it here!</p>
                    <div class="center_but">
                        <a href="{% url 'triptales:add_location' %}"><button class="button-popup" role="button">Add Location</button></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Popup code end -->

        <!-- Full page gradient -->
        <div id="full-page-gradient">
            <div class="content-container">
                {% block body_block %}
                {% endblock %}
            </div>

            <!--- FOOTER -->
            <footer>
                <div class="container">
                    <footer class="py-3 my-4">
                        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                        <li class="nav-item"><a href="{% url 'triptales:index' %}" class="nav-link px-2">Home</a></li>
                        <li class="nav-item"><a href="{% url 'triptales:FAQ' %}" class="nav-link px-2">FAQs</a></li>
                        <li class="nav-item"><a href="{% url 'triptales:about' %}" class="nav-link px-2">About</a></li>
                        <li class="nav-item"><a href="{% url 'triptales:contact_us' %}" class="nav-link px-2">Contact Us</a></li>
                        </ul>
                        <p class="text-center">© 2024 TripTales, Inc</p>
                    </footer>
                    </div>
            </footer>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!-- JQuery-->
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        {% comment %} Old: <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="{% static "js/triptales-jquery.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/triptales-ajax.js" %}" crossorigin="anonymous"></script>
        
        {% comment %} This makes and error and we dont need: <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script> {% endcomment %}

        <!-- Navbar JS -->
        <script src="{% static "js/addPopup.js" %}"></script>
        {% block extra_js %}{% endblock %}
    </body>
</html>

templates/triptales/profile.html
{% extends 'triptales/base.html' %}
{% load static %}

{% block title_block %}
  {{ selected_user.username }} profile
{% endblock %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/triptales/profile.css' %}">
{% endblock %}

{% block body_block %}
{% comment %}Based on https://bbbootstrap.com/snippets/individual-user-profile-social-network-94176986 {% endcomment %}
<div class="container">
  <div class="row  pad_profile">
    <div class="col-12">
      <!-- Profile widget --> 
      <div class="bg-white shadow rounded overflow-hidden">
        <div class="px-4 pt-0 pb-5 cover">
          <div class="media align-items-end profile-head pb-5">
            <div class='row'>
              <div class="col-md-2">
                <div class="profile mr-3">
                  <div class="image-container">
                  {% if user_profile.picture.name %}
                    <img class="rounded mb-2 img-thumbnail" src="{{ MEDIA_PROFILE_IMG_URL }}{{ user_profile.picture.url }}" alt="{{ selected_user.username }}'s profile image" width="200" />
                  {% else %}
                    <img class="rounded mb-2 img-thumbnail" src="{% static 'images/profile_default_img.png' %}" alt="Default profile image" width="200" />
                  {% endif %}
                  </div>
                </div>
              </div>

              <div class='col-md-9'>
                <div class="media-body mb-5 text-white">
                  <h4 class="mt-0 mb-0">{{ selected_user.username }} </h4> <p class="small mb-4">
                    <i class="fas fa-map-marker-alt mr-2">{{ user_profile.bio }}</i>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="bg-light p-4 d-flex justify-content-center text-center">
          <ul class="list-inline mb-0">
            <li class="list-inline-item">
              <h5 class="font-weight-bold mb-0 d-block">{{ user_posts|length }}</h5><small class="text-muted"><i class="fas fa-image mr-1"></i>Posts</small>
            </li> <li class="list-inline-item">
              <h5 class="font-weight-bold mb-0 d-block">{{ liked_posts|length }}</h5><small class="text-muted"><i class="fas fa-user mr-1"></i>Like Posts</small>
            </li> <li class="list-inline-item">
              <h5 class="font-weight-bold mb-0 d-block">{{ saved_posts|length }}</h5><small class="text-muted"><i class="fas fa-user mr-1"></i>Saved Posts</small>
            </li>
          </ul>
        </div>
        
        <div class="px-4 py-3">
          <h5 class="mb-0">Biography</h5>
          <div class="p-4 rounded shadow-sm bg-light">
            {% if user_profile.bio %}
              <p class="font-italic mb-0">{{ user_profile.bio }}</p>
            {% else %}
              <p class="font-italic mb-0">This user has not written a bio yet.</p>
            {% endif %}
          </div>
        </div>
        <div class="py-4 d-flex justify-content-center">
          {% if selected_user == user %}
          <a href="{% url 'triptales:edit_profile' %}" class="btn btn-sm btn-block">
            <button class="button-nav" role="button">Edit profile</button>
          </a>
          <a href="{% url 'auth_password_change' %}" class="btn btn-sm btn-block">
            <button class="button-nav" role="button">Change Password</button>
          </a>
          {% endif %}
        </div>

        <div class="row py-4 px-4">
          <div class="container">
            <div class="row">
              {% if selected_user == user %}
              <div class="col-md-4">
                <div class="card md-4">
              {% else %}
              <div class="col-md-6">
                <div class="card md-6">
              {% endif %}
                  <div class="card-body">
                    <h2>User Posts</h2>
                    <p class="card-text">
                      {% if user_posts %}
                        {{ user_posts|length }} posts<ul class="list-group">
                          {% for post in user_posts %}
                            <li class="list-group-item">
                              <a href="{% url 'triptales:post_detail' post.id %}">{{ post.location.name }}</a>
                            </li>
                          {% endfor %}
                        </ul>
                      {% else %}
                        {% if selected_user == user %}
                          The posts you write will appear here. Click <a href="{% url 'triptales:create_post' %}">here</a> to write a new post.
                        {% else %}
                          {{ selected_user.username }} has not written any posts yet.
                        {% endif %}
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
              {% if selected_user == user %}
              <div class="col-md-4">
                <div class="card md-4">
              {% else %}
              <div class="col-md-6">
                <div class="card md-6">
              {% endif %}
                  <div class="card-body">
                    <h2>Liked Posts</h2>
                    <p class="card-text">
                      {% if liked_posts %}
                        {{ liked_posts|length }} liked posts<ul class="list-group">
                          {% for post in liked_posts %}
                            <li class="list-group-item">
                              <a href="{% url 'triptales:post_detail' post.id %}">{{ post.location.name }}</a>
                            </li>
                          {% endfor %}
                        </ul>
                      {% else %}
                        {% if selected_user == user %}
                          The posts you like will appear here.
                        {% else %}
                          {{ selected_user.username }} has not liked any posts yet.
                        {% endif %}
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
              {% if selected_user == user %}
              <div class="col-md-4">
                <div class="card md-4">
                  <div class="card-body">
                    <h2>Saved Posts</h2>
                    <p class="card-text">
                    <div class="alert alert-info" role="alert">
                      <span data-feather="info"></span> You are the only one who can see your saved posts.
                    </div>
                      {% if saved_posts %}
                        {{ saved_posts|length }} saved posts<ul class="list-group">
                          {% for post in saved_posts %}
                            <li class="list-group-item">
                              <a href="{% url 'triptales:post_detail' post.id %}">{{ post.location.name }}</a>
                            </li>
                          {% endfor %}
                        </ul>
                      {% else %}
                        The posts you save will appear here.
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/triptales/profile_registration.html
{% extends 'triptales/userprofile_form_base.html' %}

{% block form_h1 %}
    Complete your profile registration
{% endblock %}

{% block form_action %}{% url 'triptales:register_profile' %}{% endblock %}

{% block form_inputValue %}Complete registration{% endblock %}